package finance.entity;
// Generated Nov 29, 2015 12:39:27 PM by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;





/**
 * Account generated by hbm2java
 */
@XmlRootElement
public class Account  implements java.io.Serializable {


     private Integer uid;
     private String name;

    public Account() {
    }

    public Account(String name) {
       this.name = name;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


