package finance.entity;
// Generated Nov 29, 2015 12:39:27 PM by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;




/**
 * AccountSetting generated by hbm2java
 */
@XmlRootElement
public class AccountSetting  implements java.io.Serializable {


     private Integer uid;
     private int accountId;
     private String fileHeader;

    public AccountSetting() {
    }

    public AccountSetting(int accountId, String fileHeader) {
       this.accountId = accountId;
       this.fileHeader = fileHeader;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public int getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }
    public String getFileHeader() {
        return this.fileHeader;
    }
    
    public void setFileHeader(String fileHeader) {
        this.fileHeader = fileHeader;
    }




}


