package finance.entity;
// Generated Nov 29, 2015 12:39:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * BudgetCategory generated by hbm2java
 */
@XmlRootElement
public class BudgetCategory  implements java.io.Serializable {


    private Integer uid;
    private int budgetId;
    private int categoryId;
    private BigDecimal amount;

    public BudgetCategory() {
    }

    public BudgetCategory(int budgetId, int categoryId, BigDecimal amount) {
       this.budgetId = budgetId;
       this.categoryId = categoryId;
       this.amount = amount;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    
    public int getBudgetId() {
        return this.budgetId;
    }
    
    public void setBudgetId(int budgetId) {
        this.budgetId = budgetId;
    }
    
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

}


