package finance.entity;
// Generated Nov 29, 2015 12:39:27 PM by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;




/**
 * Category generated by hbm2java
 */
@XmlRootElement
public class Category  implements java.io.Serializable {


     private Integer uid;
     private String name;
     private int sortId;
     private Boolean extra;

    public Category() {
    }

    public Category(String name, int sortId, Boolean extra) {
       this.name = name;
       this.sortId = sortId;
       this.extra = extra;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getSortId() {
        return this.sortId;
    }
    
    public void setSortId(int sortId) {
        this.sortId = sortId;
    }
    
    public Boolean getExtra() {
        return extra;
    }

    public void setExtra(Boolean extra) {
        this.extra = extra;
    }




}


