package finance.entity;
// Generated Nov 29, 2015 12:39:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Transaction generated by hbm2java
 */
@XmlRootElement
public class Transaction  implements java.io.Serializable {


    private Integer uid;
    private Date effdate;
    private Date postdate;
    private Date transdate;
    private BigDecimal amount;
    private String vendor;
    private String description;
    private Account account;
    private Category category;
    private Boolean deleted;
    private int splitId;
     

    public Transaction() {
    }

    public Transaction(Date effdate, Date postdate, Date transdate, BigDecimal amount, String vendor, String description,
            Boolean deleted, int splitId) {
       this.effdate = effdate;
       this.postdate = postdate;
       this.transdate = transdate;
       this.amount = amount;
       this.vendor = vendor;
       this.description = description;
       this.deleted = deleted;
       this.splitId = splitId;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public Date getEffdate() {
        return this.effdate;
    }
    
    public void setEffdate(Date effdate) {
        this.effdate = effdate;
    }
    public Date getPostdate() {
        return this.postdate;
    }
    
    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }
    public Date getTransdate() {
        return this.transdate;
    }
    
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getVendor() {
        return this.vendor;
    }
    
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public int getSplitId() {
        return splitId;
    }

    public void setSplitId(int splitId) {
        this.splitId = splitId;
    }

}


